# Generated by Django 3.2.15 on 2022-10-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('seller', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nearbyAmenities', models.TextField()),
                ('availableUnits', models.IntegerField(null=True)),
                ('plotsize', models.CharField(choices=[('40*90', '40*90'), ('50*100', '50*100'), ('100*100', '100*100')], default='', max_length=30)),
                ('images', models.FileField(upload_to='plots/projectimages/')),
                ('sellingprice', models.IntegerField(null=True)),
                ('discountprice', models.IntegerField(null=True)),
                ('deposit', models.IntegerField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotNumber', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('imageonMap', models.FileField(null=True, upload_to='plots/plotimages/')),
                ('price', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.plot')),
            ],
        ),
    ]
