# Generated by Django 3.0.3 on 2022-10-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_plot_number_bookedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_number',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
