# Generated by Django 3.2.15 on 2022-10-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('residential_status', models.CharField(choices=[('R', 'Resident'), ('NR', 'Non-Resident')], max_length=2, null=True)),
                ('current_address', models.CharField(max_length=100, null=True)),
                ('national_id', models.CharField(max_length=10, null=True, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('kra_pin', models.CharField(max_length=11, null=True, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('buyer_personal_number', models.CharField(max_length=50, null=True)),
                ('buyers_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mobile_phone', models.CharField(max_length=15, null=True)),
                ('date_of_registration', models.DateField(null=True)),
                ('contract_type', models.CharField(choices=[('Deposit + 3months', 'Deposit + 3months'), ('Deposit + 6months', 'Deposit + 6months'), ('Deposit + 12months', 'Deposit + 12months'), ('Deposit + 24months', 'Deposit + 24months'), ('OT', 'OT')], max_length=100, null=True)),
                ('deposit_amount', models.IntegerField(null=True)),
                ('balance_amount', models.IntegerField(null=True)),
                ('plot_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.plot_number')),
                ('project_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.plot')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=15, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('paidFor', models.CharField(choices=[('cash', 'cash'), ('Mpesa', 'Mpesa'), ('Check', 'Check'), ('Bank Deposit', 'Bank Deposit')], max_length=100, null=True)),
                ('paymentMethod', models.CharField(max_length=15, null=True)),
                ('dateReceived', models.DateField(null=True)),
                ('receivedBy', models.CharField(max_length=15, null=True)),
                ('paymentstatus', models.CharField(choices=[('In Process', 'In Process'), ('Received', 'Received'), ('Verified', 'Verified')], max_length=100, null=True)),
                ('paymentFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.buyerinfo')),
            ],
        ),
    ]
