# Generated by Django 3.2.15 on 2022-10-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyerinfo_registeredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpayments',
            name='paidFor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='buyerpayments',
            name='paymentMethod',
            field=models.CharField(choices=[('cash', 'cash'), ('Mpesa', 'Mpesa'), ('Check', 'Check'), ('Bank Deposit', 'Bank Deposit')], max_length=100, null=True),
        ),
    ]
