# Generated by Django 3.2.15 on 2022-10-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_auto_20221016_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinfo',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Full name'),
        ),
    ]
