# Generated by Django 3.2.15 on 2022-10-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_buyerinfo_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinfo',
            name='full_name',
        ),
    ]
