# Generated by Django 3.0.3 on 2022-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_remove_buyerinfo_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buyerpayments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
