# Generated by Django 3.0.3 on 2022-10-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_auto_20221017_1617'),
        ('buyers', '0006_auto_20221017_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerinfo',
            name='plot_booked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plots.Plot_Number'),
        ),
    ]
